const express=require('express')
const userAuth=require('../Middleware/userAuth')
const {isadmin}=require('../Middleware/sellereauth')
const userController=require('../Controller/user')
const userrouter=express.Router()
userrouter.post('/signup',userController.signup)
userrouter.post('/signin',userController.signin)
userrouter.post('/cart',userAuth,userController.usercart)
userrouter.get('/getusercart',userAuth,userController.getusercart)
userrouter.delete('/emptycart',userAuth,userController.emptycart)
userrouter.get('/applycupon',userAuth,userController.applycupon)
userrouter.post('/createorder',userAuth,userController.createorder)
userrouter.get('/getorders',userAuth,userController.getorders)
userrouter.put('/order/updateorderstatus/:id',userAuth,isadmin,userController.updateorderstatus)


userrouter.get('/getwishlist',userAuth,userController.getwishlist)
userrouter.put('/updateauser/:userid',userController.updateauser)
userrouter.get('/getallusers',userController.findalltheusers)
userrouter.get('/getauser/:userid',userController.finduserbyid)
userrouter.delete('/delete/:userid',userController.deleteauserbyid)
userrouter.get('/logout',userController.logout)
userrouter.get('/forgotpasswordtoken/:userid',userController.forgotpasswordtoken)
userrouter.put('/resetpassword/:userid',userController.resetpassword)
module.exports=userrouter
